#访问http://yourIP:8080/hello
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellogo
  template:
    metadata:
      labels:
        app: hellogo
    spec:
      containers:
        - name: hellogo
          image: zpskt/hellogo:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hellogo-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30003
  selector:
    app: hellogo
