apiVersion: v1
kind: Service
metadata:
  name: myweb
#  type=NodePort和nodePort=30001这两个属性，
#  表明service开启了NodePort方式的外网访问模式，在k8s集群之外，在本机的浏览器里，可以通过30001这个端口访问myweb（对应到8080的虚端口上）。
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: myweb